- menu_name: "Serviços"

- name: "Contato"
  url: "/contact/"
  title: "Contato"

- name: "RSS"
  url: "/feed.xml"
  title: "Inscreva-se no nosso Feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Inscreva-se no nosso Feed Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap"
